site_name: Climap 
site_description: A Rich command line utility for IMAP
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    primary: light blue
    accent: purple
  font:
    text: Work Sans
    code: Work Sans
  icon:
    repo: fontawesome/brands/git
repo_name: symonk/climap
repo_url: https://github.com/symonk/climap/
watch:
  - climap 

nav:
  - index.md
  - Developer API: reference/
plugins:
    - search
    - autorefs
    - gen-files:
        scripts:
          - docs/auto_doc_generator.py
    - literate-nav:
        nav_file: SUMMARY.md
    - section-index
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            paths: [climap]
            options:
              show_submodules: true
              line_length: 88
              show_if_no_docstring: false
              merge_init_into_class: true
              show_source: false
              docstring_section_style: table
              docstring_style: sphinx

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences